### ISSUE TITLE
Support shared folders and files

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/hapistrano#107]
capistrano has a feature to share folders and files between different releases, it is called shared folders. This feature is quite useful to preserve logs between different releases as well as overwrite configuration files, here is a quick description:

> shared contains the linked_files and linked_dirs which are symlinked into each release. This data persists across deployments and releases. It should be used for things like database configuration files and static and persistent user storage handed over from one release to the next.

**References**

https://capistranorb.com/documentation/getting-started/structure/

**Comment by CristhianMotoche** [comment]
I've never used `capistrano`. However, I assume the purpose of this is to create symlinks in our application that point to the files or directories in `shared` (I got that idea from [here](https://stackoverflow.com/questions/19071179/capistrano-how-to-put-files-in-the-shared-folder)).

Therefore, a project would have the following structure:

```
current/
   log/
       - error.log ==> link to ../../shared/log/error.log
shared/
   log/
     - error.log

releases/
  ... (all releases would also have links 
```

I think we can do this in the following way: List everything that is in `shared` and link it to each release during its creation. Of course, we would through errors if such files exist. Do you think that is a good approach? @sestrella @juanpaucar

**Comment by sestrella** [comment]
@CristhianMotoche regarding:

> List everything that is in shared and link it to each release during its creation

capistrano only links the files declared at `linked_files` and `linked_dirs`. I'm not sure about linking everything inside `shared` since in some cases it's necessary to link the whole directory instead, like the log folder, for instance.

**Comment by CristhianMotoche** [comment]
Oh, ok. @sestrella Then, we should work on adding `linked_files` and `linked_dirs` entries to the `config.yml` file.

**Comment by CristhianMotoche** [comment]
Only for references, if someone is going to work on this issue and doesn't know capistrano. I found this [useful](https://www.talkingquickly.co.uk/2014/01/deploying-rails-apps-to-a-vps-with-capistrano-v3/):

> `# files we want symlinking to specific entries in shared.`
> `set :linked_files, %w{config/database.yml config/application.yml}`
> `# dirs we want symlinking to shared`
> `set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}`
>
> Means that after every deploy, the files listed in the array (remember %w{items} is just shorthand for creating an array of string literals) will be automatically symlinked to corresponding files in shared.

**Comment by CristhianMotoche** [comment]
In favor of #109
