### ISSUE TITLE
Add an option to avoid checkout source code from git 

### ISSUE THREAD

**Issue by nickovivar** [stackbuilders/hapistrano#116]
We need to add an option to avoid check out the source code during deployment. 
We should choose if we want to check out the code from GH or just move a folder with all the files to deploy the application.

For instance, if a project builds the application in CIrcle CI, hapistrano could move the project folder to the server instead of checking out the code and build the application again in the server.

**Comment by ibarrae** [comment]
Would it make sense to refactor the configuration file to something like:
```yaml
....
external-repository:
  url: 
  revision:

local-directory:
...
```
All these values would be optional, but it would require at least one of them
Then when loading up the configuration, if the `local-directory` is a valid directory it will copy all the files inside of it or it will continue working with `checkout`... and everything as before?

**Comment by ibarrae** [comment]
FYI @juanpaucar, I didn't find any configuration related to "copying a directory" instead of taking the contents from a project with source control. Furthermore, one of the [requirements](https://github.com/capistrano/capistrano/blob/master/README.md#requirements) of using *capistrano* is to have a project that uses source control.

What I _did found_ is that you can have plugins for capistrano, and I found this [one](https://github.com/ekho/capistrano-scm-local) that allows the deployment from a local directory.

Hope this helps :smile:

**Comment by juanpaucar** [comment]
@nickovivar For the scenario that you are describing, you could simply copy the necessary compiled files with 
```yaml
copy_files:
  - src: '/home/stackbuilders/my-file.txt'
    dest: 'my-file.txt'
copy_dirs:
  - src: .stack-work
    dest: .stack-work
```

@ibarrae  I don't think that we should have a breaking change for this or change the current syntax that "deploy yaml" files have. However, I do think that it's a good chance to start supporting other version control sources, including a local one. See #12 

This should be kind of a large change for the library. It should essentially change the commands we execute, depending on the version control system. Once that gets decoupled, the commands for a local copy/paste working as a version control system would be a trivial addition. 

Does it sound reasonable to you? @nickovivar  @ibarrae let me know your thoughts

**Comment by ibarrae** [comment]
I think that using `copy_dirs` won't place the contents of the directory under `<deployment-path>/repo` or at least that's what I understood from @nickovivar request.

> For instance, if a project builds the application in CIrcle CI, hapistrano could move the project folder to the server instead of checking out the code and build the application again in the server.

Furthermore, as stated by @nickovivar, we should _build the application again in the server_, and with my current understanding of the codebase all the commands listed under `build_script` will run under the `<deploy-path>/<release>`.

**Comment by nickovivar** [comment]
@juanpaucar It is possible to have an option to don't make a git checkout? You're right about that we can use the options `copy_files / copy_dirs` to move the files from our CI machine to the deploy server, but we get an error if we don't specify a git repository. cc @ibarrae

**Comment by ibarrae** [comment]
I will push some changes to review this, and if everything is ok, I will add some tests and update the documentation accordingly @juanpaucar.

**Comment by juanpaucar** [comment]
@ibarrae After reviewing #135 I think that it won't close this issue. However, it's a good extension to Hapistrano and we can merge it. Also, as it is right now, it's a great first step to solve #12. So, thanks for the Pull Request

@nickovivar Please, correct me if I'm getting wrong something here. You are suggesting to keep `git` as the source, but making the repo checkout optional.

**Comment by nickovivar** [comment]
I think this approach solves the original issue if we can avoid make a git checkout. Thanks @ibarrae
