### ISSUE TITLE
Implement support for version control systems other than git

### ISSUE THREAD

**Issue by jsl** [stackbuilders/hapistrano#12]
Currently only git is supported, but it would be nice to have support for systems like darcs.

**Comment by jpvillaisaza** [comment]
Re-learning some Darcs (or just learning, I think it's changed a lot) should be nice, or at least fun.

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement support for version control systems other than git](https://trello.com/c/ojPCwXW2/52-implement-support-for-version-control-systems-other-than-git)

**Comment by CristhianMotoche** [comment]
Hello @jsl @jpvillaisaza This issue has been open for a long time now. Do you think it is worth to invest the effort on supporting a different VCS?
