### ISSUE TITLE
Allow to add extra flags to the SSH connection

### ISSUE THREAD

**Issue by juanpaucar** [stackbuilders/hapistrano#120]
Different servers might have different configurations for the ssh connections, so we might want to add the option for `non-login` and `non-interactive`. We might also consider additional options

**Comment by juanpaucar** [comment]
@speedlight Do you consider that we should add other connection options additional to the previously mentioned options?

**Comment by speedlight** [comment]
> @speedlight Do you consider that we should add other connection options additional to the previously mentioned options?

@juanpaucar I think with this is good to have more control of how ssh session are started.

**Comment by CristhianMotoche** [comment]
Close do to #122
