### ISSUE TITLE
Travis CI failing OSX due to homebrew

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hapistrano#124]
We are using [homebrew](https://github.com/stackbuilders/hapistrano/blob/master/.travis.yml#L29) to install ghc, but it's failing during the [script](https://travis-ci.org/stackbuilders/hapistrano/jobs/603333326#L1881) because it's trying to use Cabal 3.0  and GHC 8.8 (I created a separated [issue for that](https://github.com/stackbuilders/hapistrano/issues/123)).

**Comment by juanpaucar** [comment]
Solved by #126
