### ISSUE TITLE
Don't know how to use the docker image

### ISSUE THREAD

**Issue by hughjfchen** [stackbuilders/hapistrano#129]
Currently, the docker image only contain hap and ssh client, not has a even bash. When I feed the docker image with a config file which has run_locally or/and build_script, it always report that it can't find `exec`. Even with the following minimal config, it also complains `exec` not found:

```
deploy_path: '/home/chenjf/hap-sandbox'
# host: myserver.com
# port: 2222
repo: 'https://github.com/shapp-alliance/backend.git'
revision: origin/master
# shell: bash
# ssh_args: 
#build_script:
#  - echo Done
# restart_command: systemd restart my-app-service
vc_action: true
linux: true
release_format: short
keep_releases: 5
linked_files: 
linked_dirs: 
#run_locally: 
#  - /usr/bin/ssh -v
```

I run the docker image with following command:
```
docker run -it --rm -v /home/chenjf:/home/chenjf stackbuilders/hapistrano deploy -c /home/chenjf/deploy-config-for-test.yaml
```

and got following error:
```
*** localhost ******************************************************************
hap: bash: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by hughjfchen** [comment]
Well, think more and I believe we should put the `hapistrano` static executable in a separate directory, e.g. `/hapistrano` and let the user bind mount the host `/bin` and `/usr/bin` to the docker container so that commands on the host machine can be accessed within the docker container. We need to do following:

- [ ] change the `Dockerfile` to mkdir `/hapistrano`, and copy the static executable under this directory

- [ ] update the `Readme` and provide a sample command to tell how to use it

**Comment by juanpaucar** [comment]
Hi @hughjfchen thanks for your recommendation. We might need to add extra information for the usage with docker. Currently, it has a fixed entry point directly to the hapistrano binary. If you need an interactive shell you could overwrite the entry point; the hapistrano image is based on Alpine.

```sh
docker run -it --rm --entrypoint /bin/sh -v $PWD/hap.yaml:/root/hap.yaml stackbuilders/hapistrano
```

Usually, you shouldn't need to run it interactively and something like this might be enough for most use scenarios,
```sh
docker run --rm -v $PWD/hap.yaml:/hap.yaml stackbuilders/hapistrano deploy
```

Thanks to your report we found about #130, so, for now, to get it working you will also need to add the `host` as `localhost` on the configuration file until we ship a new version with this issue fixed

```yaml
host: localhost
````

Please, let me know if this comment was of any help or if this doesn't solve your current scenario.

**Comment by CristhianMotoche** [comment]
I'll be closing this issue in case the above comment solved it. Feel free to open it's not resolved yet.
