### ISSUE TITLE
Create releases with pre-compiled binaries

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/hapistrano#133]
`hapistrano` is meant to be used as an executable, therefore, in order to simplify the installation process, we could provide pre-compiled binaries so end-users could just download and copy the binary instead of installing the whole package via `stack` or `cabal`.

**Documentation**
- https://help.github.com/en/github/administering-a-repository/creating-releases
- https://docs.travis-ci.com/user/deployment/releases/

**References**
- https://github.com/commercialhaskell/stack/releases

**Comment by CristhianMotoche** [comment]
Hey @sestrella ! @nickovivar and I will take this!
