### ISSUE TITLE
Share sandbox if dependencies haven't changed between deployments

### ISSUE THREAD

**Issue by juanpaucar** [stackbuilders/hapistrano#14]
Currently it may take a while to get all the dependencies installed when we deploy, even if we haven't changed anything in the cabal file at all. In Capistrano this is kind of solved by the user if the user creates a symlink `vendor/bundle` to `shared/vendor_bundle`
> so that bundler will share your installed gems between deployments (making things zippy if you didn't make any changes), but still give you the benefits of isolation from other applications.

In hapistrano an option that enables a shared cabal sandbox for deployments where no dependency has changed, would be really useful

**Comment by sestrella** [comment]
This is how `capistrano-bundler` works https://github.com/capistrano/bundler/blob/master/lib/capistrano/tasks/bundler.cap

**Comment by jpvillaisaza** [comment]
Stack could be an option here, as suggested by @jsl. I have to take a closer look at how the application works and see if it fits, but I think it does.

**Comment by jsl** [comment]
This issue is resolved - we use currently Stack with Hapistrano on most of our projects.
