### ISSUE TITLE
Which user is used on the remote machine?

### ISSUE THREAD

**Issue by saurabhnanda** [stackbuilders/hapistrano#146]
A ctrl+f `user` on the README at https://hackage.haskell.org/package/hapistrano doesn't turn-up anything useful. Are all commands executed on the remote machine as the `root` user? Is there any way to change that?

**Comment by juanpaucar** [comment]
Hi @saurabhnanda , that's a good observation. It doesn't seem immediately obvious how it will connect or how it will run the commands. I will improve that. Meanwhile, please take a look at a real world example:

https://github.com/stackbuilders/tutorials/blob/tutorials/deploy/staging.yml

There you can see that the values on `host` will tell hapistrano how to connect to the server. That's the starting point about who is running the commands on the remote server. Please let me know if you need further clarification

**Comment by CristhianMotoche** [comment]
We've improved the README to clarify how you can specify the user that connects to the repository. I'll be closing this issue for now.
