### ISSUE TITLE
Adding Table of Content to Readme.md 

### ISSUE THREAD

**Issue by ng29** [stackbuilders/hapistrano#147]
Hey @jsl / @mrkkrp 

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

I would like to work on this issue.

**Comment by juanpaucar** [comment]
Hi @ng29 , please go ahead

**Comment by ng29** [comment]
> Hi @ng29 , please go ahead

TOC is ready to serve 👍

**Comment by juanpaucar** [comment]
Closed by #148
