### ISSUE TITLE
Delete old release only after a successful deployment

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/hapistrano#154]
Right now hapistrano only deletes old releases after a successful deployment, therefore, old releases could pile up while trying out a deployment script for the first time. Perhaps this behavior should be revisited in order to run the clean-up tasks always  (when the deployment is successful or when it fails)

**Comment by CristhianMotoche** [comment]
Thanks @sestrella for reporting this. Could you please elaborate on this:
> this behavior should be revisited in order to run the clean-up tasks always 
?

I want to make sure I understand correctly. AFAIK, every time you run `hap deploy` it creates a new deploy folder where the build script is executed. Therefore, old releases shouldn't affect that.

Also, I think it's correct to remove old releases only when there is a successful deployment. I don't think we should remove old releases when the release fails. We could run out of old correct releases and that could affect rollbacks.

**Comment by sestrella** [comment]
Sure, let me provide more context. Usually, when a Developer is setting up Hapistrano for the first time in a project, there is a lot of try and error involved, which could easily fill the disk since Hapistrano only deletes the X number of releases specific by `keep_releases` after a successful release. On the other hand, preserving the latest failed release folder is important for troubleshooting purposes, so I think the proposal here is to preserve only the latest failed release and delete the others while keeping the successful releases untouched. So let's consider the following scenario:

```
- S1
- S2 -> current
- F1
```

S = successful release, F = failed release

If another deployment attempt fails, right now the release folder would look like this:

```
- S1
- S2 -> current
- F1
- F2
```
But after this issue, it would look like this:
```
- S1
- S2 -> current
- F2
```

Right now [dropReleases](https://github.com/stackbuilders/hapistrano/blob/ef9df6183dc492a0084ad1b8d3c4a41f24c405ea/app/Main.hs#L168) is only triggered after `activateRelease` if there are no errors.

**Comment by DavidMazarro** [comment]
Hi all, I intend on taking a look at this. I was wondering, is this expected to be the new default behavior of `hap deploy`, or should a new boolean flag be added to the config? (i.e. `delete_failed_releases: yes`)

**Comment by CristhianMotoche** [comment]
Hey @DavidMazarro I prefer to have a boolean flag for this. I think a flag in the command line:
`hap deploy --keep-succeeds` could be better. What do you think?

**Comment by DavidMazarro** [comment]
Hi @CristhianMotoche, I think it's better too, both for compatibility and ability to opt-in/out of this behavior.
