### ISSUE TITLE
Authenticate pull requests in docker hub

### ISSUE THREAD

**Issue by felixminom** [stackbuilders/hapistrano#156]
We need to authenticate our pull request in order to test our builds. 

With @sestrella we realized that some of our builds in travis were failing due to a docker hub issue, when looking deeper into it we ended up with this article https://www.docker.com/increase-rate-limits 

In synthesis we need to authenticate our PRs to be able to pull images from docker hub without any limit impediment.

**Comment by ibarrae** [comment]
I can take care of this issue @felixminom @juanpaucar :+1:

**Comment by sestrella** [comment]
@ibarrae I wonder if this is a good time to consider moving to GH actions, so far it looks like there is an official Docker action for this https://github.com/docker/login-action#dockerhub

**Comment by ibarrae** [comment]
> @ibarrae I wonder if this is a good time to consider moving to GH actions, so far it looks like there is an official Docker action for this https://github.com/docker/login-action#dockerhub

That sounds great, tried to keep changes minimal but I'll close the previous PR and work on a new one with GH actions :rocket:
