### ISSUE TITLE
Separate `build-and-test` from the release process

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hapistrano#181]
Currently, there is one single workflow file that does everything. Unfortunately, this causes some issues when the contribution comes from an external members because the step where hapistrano is built on a docker container fails. Let's separate [these lines](https://github.com/stackbuilders/hapistrano/blob/db27a71f3d903c2e1b0e78e6d700e04012bfab28/.github/workflows/build-and-test.yml#L55-L65) from the main workflow.

**Comment by sestrella** [comment]
Solved by #183
