### ISSUE TITLE
Deploying to multiple machines concurrently not working

### ISSUE THREAD

**Issue by tittoassini** [stackbuilders/hapistrano#210]
The parallel deployment does not seem to work (anymore, it used to), the deployment seem to take place only on the first target.

The yaml:

deploy_path: "/home/ubuntu/app/top-test"
repo: "https://github.com/Quid2/top-apps"
revision: origin/master
targets:
  - host: ubuntu@nano.quid2.org
  - host: ubuntu@net.quid2.org
build_script:
  - sudo apt install zlib1g-dev
  - stack setup
  - stack build --local-bin-path bin --copy-bins
restart_command: sudo killall --quiet --signal SIGKILL top-test;cd /home/ubuntu/app/top-test/current;bin/top-test </dev/null >/dev/null 2>&1 &

hap --version
Hapistrano: 0.4.6.0
branch: master
revision: d4ebd86db5761cccf2d267f3d4a684d5a0ac4852

**Comment by sestrella** [comment]
@tittoassini thank you for reporting this back, I found the same issue while working on a project

**Comment by CristhianMotoche** [comment]
This was fixed on the last hapistrano releases. Thanks for reporting it.

**Comment by sestrella** [comment]
@CristhianMotoche awesome! Thank you for taking care of this issue
