### ISSUE TITLE
Add init command that creates a hap.yml file

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hapistrano#224]
It would be nice to have a command that automatically generates a Yaml sample file:

```
$ hapistrano init
> Generated sample hap.yml file
$ cat hap.yml
host: user@myserver.com
port: 2222
repo: 'https://github.com/user/repo.git'
revision: origin/main
build_script:
  - echo 'Build steps'
restart_command: echo 'Restart command'
```

It won't overwrite the existing file:
```
$ hap init
> ERROR: There is already a hap.yml file in the current directory.
```

**Comment by FranzGB** [comment]
Hey @CristhianMotoche this looks fun. I think I can do it. Could you please assign me this issue?

**Comment by CristhianMotoche** [comment]
Hi @FranzGB Thanks for the initiative. There is already a PR (#227) for this, though. Sorry.

**Comment by FranzGB** [comment]
No worrie. Glad that this has been tackled. Great initiative 🙌
