### ISSUE TITLE
Prompt user to create hap.yml file

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hapistrano#225]
If we implement #224 then it would be even better to have a prompt that requests the user for basic information to create the `hap.yml` file:

```
$ hap init
> repo: 'https://github.com/user/repo.git'
> revision (default: origin/main): production
> host (default: root@localhost): user@myserver.com
> port (default: 22): 2222
> Include restart command (y/n)?: y

> Generated hap.yml file

$ cat hap.yml file
> Generated sample hap.yml file
$ cat hap.yml
host: user@myserver.com
port: 2222
repo: 'https://github.com/user/repo.git'
revision: origin/main
build_script:
  - echo 'Build steps'
restart_command: echo 'Restart command'
```

I think `repo` is the only required property. The other ones could have a default value that the user can change eventually.

(Optional) Also, to create a file with all the default values we could include a flag:
```
$ hap init -y
> Generated hap.yml file 
```

**Comment by CristhianMotoche** [comment]
There is already an implementation for this which was kindly added in a2aa3dba432dc1ad49844cca0f0abc18980c2cc3 but it needs some refinements:

1. `hap.yml` file is always created even if the given value is not of the correct type
2. The parser is using `read` so Text values need to be wrapped in quotes which can be annoying:

```
Creating 'hap.yml'
repo (default: git@github.com:stackbuilders/hapistrano.git)?:
"git@github.com:stackbuilders/my-repo.git"
```

Therefore, I'll leave this issue open to solve those two inconveniences first.

**Comment by alexisbcc** [comment]
@CristhianMotoche  BTW do you think that implementing `repo` as the only required value should be good?
The second point (`-y` flag to default all) sounds reasonable, I'm going to work on that.

**Comment by CristhianMotoche** [comment]
Thanks @alexisbcc I see you already worked on this, so I'll close this ticket. Thank you!
