### ISSUE TITLE
Add a mechanism for migrating a database, or adding other tasks during the deploy process

### ISSUE THREAD

**Issue by jsl** [stackbuilders/hapistrano#27]
One of the most common use-cases for capistrano is running a task, like a database modification, before symlinking the new release into place. Actually they support both `before` and `after` hooks. We should make sure that we have similar functionality for extending the build pipeline. Additionally, if we add multi-host deploy support, we should have the capability to run certain commands, like database migrations, on only one host.

Once we support hooks into the deploy cycle, and multi-host deploy, it seems like hapistrano probably has most of the important features that people rely on in capistrano projects.

**Comment by lpaulmp** [comment]
Would be nice if Hapistrano allow to do some task *before* or *after* create symlinks to ```current``` folder. I faced situations that restart services or change configuration before create the symlink, was need, and those kind of features helped me a lot.

**Comment by jsl** [comment]
@lpaulmp I think that you can currently do this by modifying `RESTART_COMMAND`. Would that work for you?

**Comment by jsl** [comment]
We're currently doing migrations by calling `moo` from our build scripts. Closing since this issue is resolved.
