### ISSUE TITLE
Consider using a scripting library

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/hapistrano#28]
There seem to be some problems with using this library in different operating systems, as described in, for instance, issue #25.

I wonder if it would make sense to redefine some functions using a scripting library such as [shelly](https://hackage.haskell.org/package/shelly) or [turtle](https://hackage.haskell.org/package/turtle) (taking into account Gabriel Gonzalez's mature rating for the [scripting category](http://www.haskellforall.com/2015/08/state-of-haskell-ecosystem-august-2015.html#scripting-command-line-applications) in the [state of the Haskell ecosystem](http://www.haskellforall.com/2015/08/state-of-haskell-ecosystem-august-2015.html)).

Right now, the test suite is failing on Linux (Ubuntu) for me. The issue can be fixed easily for GHC 7.10.2 with process >= 1.2.3.0, but would require a little more work for older versions (do you we want to support older versions?).

I think we can solve everything with the process library, but we can think if there are enough benefits with moving to something like turtle or shelly.

As a separate (related) issue, there are libraries we can use to handle more command-line options.

**Comment by jpvillaisaza** [comment]
@jsl Would it make sense to handle command-line options with either turtle or simply getopt (from base)? It should be very simple (especially with turtle) and we'd get --help and -h flags, as well as an appropriate usage message.

We only have "deploy" and "rollback" as options right now, but it would be easy to add new ones. turtle makes it trivial, but requires extra dependencies. getopt is a little less trivial, but dependencies wouldn't change.

If it makes sense, I'll open a new issue.

**Comment by jsl** [comment]
We should discuss the pros and cons of the libraries that you mentioned with something like Shake. I agree that Hapistrano could be re-written in a library that improves interaction with the shell.

**Comment by jpvillaisaza** [comment]
@jsl Sure, at least for the first part, which is the one directly related to this issue, but I don't remember much of it. There's a second part (which should be a separate issue) related to command line arguments. For that, we can use cmdargs or a similar library for better documenting the different Hapistrano commands (and adding basic ones like `hap --help` to print a help message).

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consider using a scripting library](https://trello.com/c/T7UV06rT/47-consider-using-a-scripting-library)

**Comment by CristhianMotoche** [comment]
Hey @jpvillaisaza Have you noticed if the test suite keeps failing now? Should we consider using one of the scripting libraries that you mention? Or, should we close the issue now that we're using [process >= 1.4](https://github.com/stackbuilders/hapistrano/blob/master/hapistrano.cabal#L64-L65)?

**Comment by jpvillaisaza** [comment]
@CristhianMotoche I don't know. I guess the tests are working fine—the linked issue was fixed and this looks like a follow up. I'm okay with closing.

**Comment by CristhianMotoche** [comment]
Thanks for the quick reply @jpvillaisaza I'll close it for now.
