### ISSUE TITLE
Which versions of GHC should we support

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hapistrano#36]
Right now the application is tested with GHC 7.6.3, 7.8.4, and 7.10.1. Should we still worrying about GHC 7.6.3? If so, we could continue using `cabal` in `travis`, otherwise we could switch to `stack`.

This issue should be consider in the other OS projects.

**Comment by jpvillaisaza** [comment]
@CristhianMotoche 7.8 (7.8.4) and 7.10 (7.10.3) sounds good to me.

**Comment by CristhianMotoche** [comment]
I'll close this issue, since #37 .
