### ISSUE TITLE
Support comments and empty lines

### ISSUE THREAD

**Issue by juanpaucar** [stackbuilders/hapistrano#41]
Currently hapistrano will fail if there are comments in the building files. The same will happen with empty lines.

This should be a enhancement since sometimes it's better to have comments and empty lines that make easier the reading. This is related to how we pass the lines arguments to the `buildRelease` function 

``` Haskell
buildRelease :: Release  -- ^ The Release to build
             -> [String] -- ^ Commands to be run. List intercalated
                         -- with "&&" so that failure aborts the
                         -- sequence.
             -> Hapistrano ()
buildRelease rel commands = do
  conf <- ask
  let cdCmd = "cd " ++ releasePath conf rel
  void $ runCommand (host conf) $ intercalate " && " $ cdCmd : commands

```

**Comment by mrkkrp** [comment]
Resolved via #44.
