### ISSUE TITLE
Add command line arguments

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/hapistrano#43]
A part of #28 is about adding command line arguments such as `--help` to at least display some usage information. I chose cmdargs for a project I added command line arguments recently, but a similar one would work as well. Basic options (help, version, ...) are good enough to start, but there are a lot of nice ones we can add.

Some ideas after a quick look at Capistrano:
- `--dry-run` to do a dry run
- `--print-config-variables` to display the configuration before deploying

**Comment by mrkkrp** [comment]
I would vote for `optparse-applicative` as well, it's hard to find anything better than this.

**Comment by jpvillaisaza** [comment]
@CristhianMotoche One of the things I like about cmdargs is that is has almost no dependencies (base, filepath, process, template-haskell, and transformers, which are all boot libraries). But this is not a very important advantage over optparse-applicative (which has as non-boot library dependencies ansi-wl-pprint, transformers-compat, and, in some cases, semigroups).

So, both are fine as far as I'm concerned. I didn't know about bash completion with optparse-applicative, which is interesting and probably worth it (even though bash completion might not be that important for this program).

I would vote for cmdargs, which is the one I suggested, but you can go ahead with optparse-applicative following @mrkkrp's vote (and I'm guessing more people will vote for that one since it's the one we use for other programs such as dotenv).

@CristhianMotoche Would you like to start working on this and open a pull request?

**Comment by CristhianMotoche** [comment]
Hey, sorry for the late response, but sure I'd like to work on this.

**Comment by jpvillaisaza** [comment]
@CristhianMotoche Awesome, go ahead.

**Comment by jpvillaisaza** [comment]
It seems like we're using System.Console.GetOpt, but it's just a usage message without much information, so moving to something else makes more sense.

**Comment by jsantos17** [comment]
+1 optparse-applicative. @CristhianMotoche, let me know if you have any
issues :).

**Comment by mrkkrp** [comment]
Resolved via #46.
