### ISSUE TITLE
Add hook to mark application as in maintenance mode

### ISSUE THREAD

**Issue by jsl** [stackbuilders/hapistrano#45]
Even though hapistrano keeps downtime relatively low, by building in a separate directory, and then changing the "current" application symlink, there may be downtime necessary, for example, if a database migration has to take place. 

Generally, the deploy process is as follows:
- new application is built
- current running app is placed in maintenance mode
- then the schema can be migrated
- then the app can be brought back up

If you don't follow this process, application errors may occur since any given version of the code generally depends on a particular database schema.

Capistrano handles this case by allowing for a hook to bring up a maintenance page, and then to take it down once the deploy tasks are done. See the [hapistrano maintenance](https://github.com/capistrano/maintenance) library for their implementation. Hapistrano should support something similar in order to support these cases when downtime is required.

**Comment by sestrella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hapistrano - Add hook to mark application as in maintenance mode](https://trello.com/c/nlvq5Mb2/5-hapistrano-add-hook-to-mark-application-as-in-maintenance-mode)

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add hook to mark application as in maintenance mode](https://trello.com/c/ub2Pblk8/48-add-hook-to-mark-application-as-in-maintenance-mode)

**Comment by CristhianMotoche** [comment]
Hello @jsl  After taking a look at [capistrano maintenance](https://github.com/capistrano/maintenance), it seems it's used as a short hand for some simple commands:

1) `cap maintenance:enable` could be replaced with:
```
echo '<html>...' > /path/to/server/maintenace.html
# or
cp /path/to/my/maintenance.html /path/to/server/maintenace.html
```

2) `cap maintenance:disable` could be replaced with:

```
rm -rf /path/to/server/maintenace.html
```

And these could be easily added in the build script: 

```
build_script:
 - cp /path/to/my/maintenance.html /path/to/server/maintenace.html
 - db migrations
 - # another task that will affect the server
 - rm /path/to/server/maintenace.html
```

I think we could also implement something similar as `capistrano-maintenance` in `hapistrano` to quickly create a maintenance file from the command line (e.g. `hap maintenance enable/disable`). However, these could be done from the server without so much effort:

```
ssh user@server 'cp /path/to/my/maintenance.html /path/to/server/maintenace.html'
```
and
```
ssh user@server 'rm /path/to/server/maintenace.html'
```

Therefore, I don't think it's worth the effort to implement these tasks in `hapistrano`.

**Comment by CristhianMotoche** [comment]
Hello! I reviewed this internally with the team and I proposed the following two ideas:

1) Implement a `maintenance enable/disable` CLI commands in hapistrano:
`hap maintenance enable` => will create a maintenance file in a specific file
`hap maintenance disable` => will remove the maintenance file, so the proxy can keep redirecting the requests to the application

2) Implement a `with_maintenance` yaml object will run some specific tasks in the build script in maintenance mode:
```yml
build_script:
 - build
 - build_something_else
 - with_maintenance:
    steps:
       - db migrations
       - other_task_that_affects_the_server
```
The steps defined within `with_maintenance` will run while the proxy serves a `maintence.html` file.

I think both implementations can be useful. However, the second option will be a better fit for this particular issue. Therefore, we'll implement this option first.

**Comment by CristhianMotoche** [comment]
We already have a maintenance mode in hapistrano. It does something similar to what `capistrano-maintenance` does. Therefore, a user can do something like:
```
hap maintenance enable # Creates maintenance file (up to the user to set up his server to redirect the request there)
hap deploy
hap maintenance diasble # Removes maintenance file
```

There are other ways to improve this. I'll open another issue to improve the maintenance mode.
