### ISSUE TITLE
Add property-based tests

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/hapistrano#47]
Hapistrano seems like a very good candidate for adding property-based tests. I don't think this is required, just nice to have and worth the effort.

**Comment by mrkkrp** [comment]
I thinking it may be a good task for Haskell beginners to learn QuickCheck, and we could review it then.

**Comment by flandrade** [comment]
I haven't used QuickCheck. I would like to work on this, I'll submit a PR as soon as possible.

**Comment by jsl** [comment]
I think that property-based tests would be good. However, the code is likely to change quite a bit when we transition to something like Shake. Would it make sense to wait until that is done before improving the test coverage?

**Comment by jpvillaisaza** [comment]
@jsl Yes, perhaps wait until #28 is closed? (cc @flandrade)

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add property-based tests](https://trello.com/c/sa2skI89/50-add-property-based-tests)

**Comment by cptrodolfox** [comment]
I will be working on this.

**Comment by cptrodolfox** [comment]
Added three property tests with PR #128

**Comment by CristhianMotoche** [comment]
Thanks @cptrodolfox I'll be closing this issue since you already helped us with those tests. :bow:
