### ISSUE TITLE
Link/copy the .stack-work folder making the build faster

### ISSUE THREAD

**Issue by lpaulmp** [stackbuilders/hapistrano#55]
Makes hapistrano faster building the binaries in a remote host, linking/copying the previous `.stack-work` to the current release.
@sestrella I linked your comment in this issue. https://github.com/stackbuilders/hapistrano/issues/54#issuecomment-278361795

**Comment by lpaulmp** [comment]
@sestrella I'm no complete sure about the side effects of links the `.stack-work` in the rollback process, I think  we shouldn't have side effects since the binary is already build.

**Comment by mrkkrp** [comment]
I went with adding parameters that allow to specify arbitrary files and directories to copy, as it's more general and not languge-tied as linking one specific directory. Still not sure if we should close this issue or keep it open?

**Comment by lpaulmp** [comment]
@mrkkrp We can close then checked the implentation of copy `.stack-work` folder. thanks
