### ISSUE TITLE
Compile failure w/ base-4.7

### ISSUE THREAD

**Issue by hvr** [stackbuilders/hapistrano#68]
I've noticed on

http://104.239.175.197:8080/package/hapistrano

that the 0.3.* series started depending on Numeric.Natural being provided by `base`, even though it was only moved from the `nats` package starting with base-4.8; so this results in failures like:

```
Configuring component lib from hapistrano-0.3.2.0...
Preprocessing library hapistrano-0.3.2.0...

src/System/Hapistrano.hs:38:8:
    Could not find module ‘Numeric.Natural’
    It is a member of the hidden package ‘nats-0.2’.
    Perhaps you need to add ‘nats’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘nats-1.1.1’.
    Perhaps you need to add ‘nats’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
cabal: Failed to build hapistrano-0.3.2.0 (which is required by exe:hap from
hapistrano-0.3.2.0).
```

Feel free to ask me if you have any questions!

**Comment by mrkkrp** [comment]
I think we only test against 7.10 and 8.0 currently, so version of `base` in dependencies should be adjusted accordingly. I could try to extend the range of supported GHC versions though.

**Comment by juanpaucar** [comment]
@hvr Thanks for the heads up and the fixing, some packages used on rewrite of the application on version 0.3.0.0 do not allow older than 7.10 versions. @mrkkrp it seems that it required ore changes to work on older versions, also, thanks for taking the time to check this issue. Now, boundaries have been properly adjusted and matrix seems to be working fine matrix.hackage.haskell.org/package/hapistrano.
