### ISSUE TITLE
Stream the log of commands to avoid CI timeout

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/hapistrano#75]
Most CI services have a timeout mechanism if a command does not return any output in an X time. Building commands such `stack build` could take a long time, therefore I think would be nice to stream the command log while the process is running.

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stream the log of commands to avoid CI timeout](https://trello.com/c/MVTV8Aip/51-stream-the-log-of-commands-to-avoid-ci-timeout)

**Comment by javcasas** [comment]
There is a function `exec'` that runs the commands. Under the hood, it uses `readProcessWithExitCode` https://hackage.haskell.org/package/process-1.2.0.0/docs/src/System-Process.html#readProcessWithExitCode that doesn't stream anything. But, copying that `readProcessWithExitCode`, we could create our tweaked version that prints to stdout in real time.

**Comment by CristhianMotoche** [comment]
I agree with @javcasas, we'll have to implement our own `readProcessWithExitCode`.  As you can see in the source code of that function:
```
readProcessWithExitCode cmd args input = do
    let cp_opts = (proc cmd args) {
                    std_in  = CreatePipe,
                    std_out = CreatePipe,
                    std_err = CreatePipe
                  }
```

the `std[in,out,err]` are always changed to `CreatePipe` and
> Create a new pipe. The returned Handle will use the default encoding and newline translation mode (just like Handles created by openFile).

I tried to create my own function that inherits the parent handle using `typed-process` but it didn't work:
https://github.com/stackbuilders/hapistrano/blob/stream-stdout/src/System/Hapistrano/Core.hs#L128

I tested running `stack exec hap -- deploy | tee stdout.txt`.

`stdout.txt` only had the output from the main process.

I'm not sure if I'm missing something here (can a process child inherit the handle of its parent?).

I looked for the `process` issues and I found this one: https://github.com/haskell/process/issues/89
I'm not sure if it's related.

Let me know what you think. \cc @sestrella @javcasas @juanpaucar

**Comment by juanpaucar** [comment]
Thanks @CristhianMotoche
