### ISSUE TITLE
Compile failures with base-4.7

### ISSUE THREAD

**Issue by hvr** [stackbuilders/hapistrano#79]
As can be seen (not anymore, as I corrected the meta-data already, see https://github.com/stackbuilders/hapistrano/issues/79#issuecomment-321195399) on

https://matrix.hackage.haskell.org/package/hapistrano

there's currently compile failures with all 0.3.* releases, i.e.

```
Configuring library for hapistrano-0.3.2.4..
Preprocessing library for hapistrano-0.3.2.4..
Building library for hapistrano-0.3.2.4..

src/System/Hapistrano.hs:38:8:
    Could not find module ‘Numeric.Natural’
    It is a member of the hidden package ‘nats-1.1.1’.
    Perhaps you need to add ‘nats’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
cabal: Failed to build hapistrano-0.3.2.4 (which is required by exe:hap from hapistrano-0.3.2.4).
```

I'm going to fixup the meta-data (by tightening the lower bound for `base` to `>=4.8`) on Hackage for the affected releases when I get back to a keyboard (unless you beat me to it).

**Comment by hvr** [comment]
I went ahead, and corrected the meta-data for the affected versions, see

 - https://hackage.haskell.org/package/hapistrano-0.3.0.0/revisions/
 - https://hackage.haskell.org/package/hapistrano-0.3.0.1/revisions/
 - https://hackage.haskell.org/package/hapistrano-0.3.1.0/revisions/
 - https://hackage.haskell.org/package/hapistrano-0.3.2.0/revisions/
 - https://hackage.haskell.org/package/hapistrano-0.3.2.1/revisions/
 - https://hackage.haskell.org/package/hapistrano-0.3.2.2/revisions/
 - https://hackage.haskell.org/package/hapistrano-0.3.2.3/revisions/
 - https://hackage.haskell.org/package/hapistrano-0.3.2.4/revisions/

So now the only thing left to do is to either address this issue in the Git version (either by tightening the lower bound on `base` or by restoring compatibility with base-4.7), so that the next release to Hackage won't regress again.

**Comment by mrkkrp** [comment]
To Hapistrano maintainers: you probably need to add a conditional dependency on `nats` for older base versions that do not have `Numeric.Natural` in them.
