### ISSUE TITLE
Deploy to multiple hosts concurrently

### ISSUE THREAD

**Issue by jsl** [stackbuilders/hapistrano#8]
We should be able to deploy to multiple hosts concurrently, eg., a web cluster that all needs to run the same release of the application.

**Comment by mrkkrp** [comment]
As a first approximation of this, we could add multi-host deploy that works sequentially (we should allow `HOST` varibale to hold a list of a sort for this). When #52 is merged, we will have very good feedback about what's going on during deploy in real time and I'm not sure what is the best way to combine output from many concurrent processes. Other than that, 100% doable. Should be add this to 0.3.0.0 milestone?
