### ISSUE TITLE
Feature request: Add local_command section

### ISSUE THREAD

**Issue by psibi** [stackbuilders/hapistrano#81]
It will contain instruction for locally running commands (in the form of shell command) before hap starts it's process of communicating with the remote server.

Why ?
My use case for deploying applications involves just copying files using hapistrano and using the `vc_action` feature specifically. So before hap starts it's process, I want to run some commands on my local system (like stack build, packaging up the application) via hap. Right now, I do it separately via shell script. Having a hook to run it via hapistrano would be great.

If I don't have any opposition, I can volunteer to implement this feature soon.

**Comment by jsl** [comment]
Hi @psibi - that sounds like a useful feature. In fact it seems to be something that [is supported in Capistrano as well](http://capistranorb.com/documentation/getting-started/local-tasks/). I think it would be great if you want to take a shot at implementing it. If you do, please also update the README file with a usage example. Thanks!

**Comment by juanpaucar** [comment]
Hi @psibi. Thanks for offering. I'm going to assign this feature to you in that case

**Comment by juanpaucar** [comment]
@psibi @jsl I'm closing this issue since it is merged and included on version 0.3.0.0 on hackage http://hackage.haskell.org/package/hapistrano-0.3.3.0
