### ISSUE TITLE
Trying to deploy to a host using `zsh` as default shell fails

### ISSUE THREAD

**Issue by nebtrx** [stackbuilders/hapistrano#84]
When you try to deploy to a host using `zsh` as default shell it fails with the following error:
```
zsh:1: no matches found: +refs/heads/*:refs/heads/*
```
That happens because `zsh` doesn't run a command at all when it fails to glob while `bash` tries to run the whole pattern unchanged. There are ways to change the default mode of `zsh`(and other shells having the same behavior) regarding this to match `bash` as explained [here](https://stackoverflow.com/a/15893007/937106) but, it won't work out of the box. 

Do you guys think it would worth to add support for running hapistrano out of the box with `zsh`(and all the shells having the same behavior)? I think it can't be quite useful for those playing with the library locally.

Let me know what you guys think of this. The solution is quite simple, it only requires to properly escape the `*` character so that the globbing would be able to find matches. Allow me to remind you that this isn't a workaround. The globbing fails as well while using `bash` but, its default behavior allows it dodge the ball. 

So, if you agree, I can push a PR adding support for `zsh`(and all the shells having the same behavior) out of the box within minutes

Cheers!

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Trying to deploy to a host using `zsh` as default shell fails](https://trello.com/c/cQ5iAUi0/46-trying-to-deploy-to-a-host-using-zsh-as-default-shell-fails)

**Comment by CristhianMotoche** [comment]
My current shell:

```
$ echo $SHELL
/usr/bin/zsh
```

After setting up `ssh` in my personal computer (`Arch OS`):

```
$ systemctl start sshd.service
```
I copied my ssh keys to `~/.ssh/authorized_keys`.

I could replicated with the following `hap.yaml`:
```yaml
deploy_path: '/tmp/hapistrano/'
host: localhost
port: 22
repo: 'https://github.com/stackbuilders/hapistrano.git'
revision: origin/master
build_script:
  - stack setup
  - stack build
linked_files:
  - .env
```


As @nebtrx mentioned, the change is simple:
```
instance Command GitFetch where
  type Result GitFetch = ()
  renderCommand (GitFetch remote) = formatCmd "git"
    [ Just "fetch"
    , Just remote
    , Just "+refs/heads/\\*:refs/heads/\\*" ]
  parseResult Proxy _ = ()
```

Although, we need to configure tests to run on a different shell as well.

**Comment by nebtrx** [comment]
Oooops, sorry for not seeing this before.
