### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by javcasas** [stackbuilders/hapistrano#90]
On some projects we download a Stack image, then build Hapistrano. This is ridiculously slow compared to having a hapistrano Docker image. We should have and share such image. I'm sure we can build it automatically and deploy it to the Docker hub.

**Comment by javcasas** [comment]
Preparing PR on https://github.com/stackbuilders/hapistrano/pull/92

**Comment by juanpaucar** [comment]
@javcasas there's another option to be considered. Using the [releases system on github](https://github.com/stackbuilders/hapistrano/releases), we might attach an executable. `stack` already generates a statically linked executable, although it only links Haskell dependencies. But we only need to add some flags to `stack` to generate a statically linked to systems dependencies.
Adding `stack build --ghc-options='-optl-static -optl-pthread'` should be enough.

I see that the PR is ready and I think is good to merge.

But, do you think it's worth to try distributing a standalone executable? Attaching a standalone executable is something I've been thinking for a while. I don't really think that the docker approach overlaps the standalone executable. The only consideration I have is to properly hash the executable to avoid malicious versions.
