### ISSUE TITLE
Hapistrano can't deploy from Windows

### ISSUE THREAD

**Issue by juanpaucar** [stackbuilders/hapistrano#96]
**Expected Behavior**
I want to deploy from Windows to a UNIX system using the same files I would use if I ran hapistrano from Linux.

**Actual Behavior**
I'm getting this error when deploying from Windows.
```
> hap deploy -c deploy/staging.yaml…Aeson exception:…Error in $['deploy_path']: InvalidAbsDir "/var/www/staging"…
```

**Other details**
Hapistrano uses the `path` library. `path` has support for windows. However, `path` [makes a distinction](https://github.com/commercialhaskell/path/blob/master/src/Path.hs ) to expose certain behavior according to the system it is being compiled on:
```hs
{-# LANGUAGE CPP #-}
#if defined(mingw32_HOST_OS)
module Path(module Path.Windows) where
import Path.Windows
#else
module Path(module Path.Posix) where
import Path.Posix
#endif
```

That means that if hapistrano is compiled on Windows, it will validate that all paths on the `server.yml` files have valid deployment paths. If the target is Unix, the path will still appear as invalid since `path`'s validation relies on the system it was compiled on.

**Comment by CristhianMotoche** [comment]
I'm going to close this issue for now since it was labeled as `wontfix`. We can reopen it in the feature since no one else has requested to take a look at it.
